name: Hugs
version: ${project.version}
main: dev.lightdream.hugs.Main
authors: [ L1ghtDream ]
website: https://lightdream.dev
softdepend:
  - LightDreamAPI
commands:
  hug:
    description: NA
  hugstop:
    description: NA
  ld-api:
    description: NA